package diff

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/fatih/color"
)

// Options for the diff command.
type Options struct {
	File1 string
	File2 string
}

// Snapshot represents a parsed envsnap markdown file.
type Snapshot struct {
	Sections map[string]*Section
	Order    []string // Preserve section order
}

// Section represents a section in the snapshot.
type Section struct {
	Name   string
	Fields map[string]string
	Order  []string // Preserve field order
}

// Run executes the diff command.
// Returns true if files are identical, false otherwise.
func Run(opts Options) (bool, error) {
	snap1, err := parseSnapshot(opts.File1)
	if err != nil {
		return false, fmt.Errorf("cannot parse %s: %w", opts.File1, err)
	}

	snap2, err := parseSnapshot(opts.File2)
	if err != nil {
		return false, fmt.Errorf("cannot parse %s: %w", opts.File2, err)
	}

	return printSemanticDiff(snap1, snap2, opts.File1, opts.File2), nil
}

// parseSnapshot parses a markdown snapshot file into structured data.
func parseSnapshot(path string) (*Snapshot, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	snap := &Snapshot{
		Sections: make(map[string]*Section),
	}

	scanner := bufio.NewScanner(file)
	var currentSection *Section
	inTable := false

	// Regex to match table rows: | key | value |
	tableRowRegex := regexp.MustCompile(`^\|\s*(.+?)\s*\|\s*(.+?)\s*\|$`)

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		// Skip metadata lines
		if strings.HasPrefix(trimmed, "_Generated by") || trimmed == "---" {
			continue
		}

		// Skip empty lines
		if trimmed == "" {
			continue
		}

		// Detect section headers (## Section Name)
		if strings.HasPrefix(trimmed, "## ") {
			sectionName := strings.TrimPrefix(trimmed, "## ")
			currentSection = &Section{
				Name:   sectionName,
				Fields: make(map[string]string),
			}
			snap.Sections[sectionName] = currentSection
			snap.Order = append(snap.Order, sectionName)
			inTable = false
			continue
		}

		// Skip main header
		if strings.HasPrefix(trimmed, "# ") {
			continue
		}

		// Detect table header
		if strings.HasPrefix(trimmed, "| Item") || strings.HasPrefix(trimmed, "|---") {
			inTable = true
			continue
		}

		// Parse table rows
		if inTable && currentSection != nil && strings.HasPrefix(trimmed, "|") {
			matches := tableRowRegex.FindStringSubmatch(trimmed)
			if len(matches) == 3 {
				key := strings.TrimSpace(matches[1])
				value := strings.TrimSpace(matches[2])
				// Skip header row
				if key != "Item" && key != "---" && !strings.HasPrefix(key, "-") {
					currentSection.Fields[key] = value
					currentSection.Order = append(currentSection.Order, key)
				}
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return snap, nil
}

// FieldDiff represents a difference in a single field.
type FieldDiff struct {
	Key    string
	Left   string
	Right  string
	Status string // "changed", "added", "removed", "same"
}

// SectionDiff represents differences in a section.
type SectionDiff struct {
	Name   string
	Diffs  []FieldDiff
	Common []FieldDiff
}

// printSemanticDiff prints a semantic comparison of two snapshots.
// Returns true if identical, false otherwise.
func printSemanticDiff(snap1, snap2 *Snapshot, file1, file2 string) bool {
	// Colors
	red := color.New(color.FgRed)
	green := color.New(color.FgGreen)
	yellow := color.New(color.FgYellow)
	cyan := color.New(color.FgCyan)
	dim := color.New(color.Faint)
	bold := color.New(color.Bold)

	// Get all unique section names
	allSections := make(map[string]bool)
	for _, name := range snap1.Order {
		allSections[name] = true
	}
	for _, name := range snap2.Order {
		allSections[name] = true
	}

	// Compute diffs for each section
	var sectionDiffs []SectionDiff
	totalDiffs := 0
	sectionsWithDiffs := 0

	// Use snap1's order, then add any sections only in snap2
	orderedSections := append([]string{}, snap1.Order...)
	for _, name := range snap2.Order {
		if snap1.Sections[name] == nil {
			orderedSections = append(orderedSections, name)
		}
	}

	for _, sectionName := range orderedSections {
		sect1 := snap1.Sections[sectionName]
		sect2 := snap2.Sections[sectionName]

		sd := SectionDiff{Name: sectionName}

		// Get all unique field names
		allFields := make(map[string]bool)
		var fieldOrder []string

		if sect1 != nil {
			for _, key := range sect1.Order {
				if !allFields[key] {
					allFields[key] = true
					fieldOrder = append(fieldOrder, key)
				}
			}
		}
		if sect2 != nil {
			for _, key := range sect2.Order {
				if !allFields[key] {
					allFields[key] = true
					fieldOrder = append(fieldOrder, key)
				}
			}
		}

		for _, key := range fieldOrder {
			var val1, val2 string
			var has1, has2 bool

			if sect1 != nil {
				val1, has1 = sect1.Fields[key]
			}
			if sect2 != nil {
				val2, has2 = sect2.Fields[key]
			}

			fd := FieldDiff{Key: key, Left: val1, Right: val2}

			switch {
			case has1 && has2 && val1 == val2:
				fd.Status = "same"
				sd.Common = append(sd.Common, fd)
			case has1 && has2 && val1 != val2:
				fd.Status = "changed"
				sd.Diffs = append(sd.Diffs, fd)
				totalDiffs++
			case has1 && !has2:
				fd.Status = "removed"
				fd.Right = "(not set)"
				sd.Diffs = append(sd.Diffs, fd)
				totalDiffs++
			case !has1 && has2:
				fd.Status = "added"
				fd.Left = "(not set)"
				sd.Diffs = append(sd.Diffs, fd)
				totalDiffs++
			}
		}

		if len(sd.Diffs) > 0 {
			sectionsWithDiffs++
		}
		sectionDiffs = append(sectionDiffs, sd)
	}

	// Print header
	if totalDiffs == 0 {
		green.Println("✓ Snapshots are identical")
		return true
	}

	fmt.Println()
	bold.Printf("Environment differences between %s and %s\n",
		filepath.Base(file1), filepath.Base(file2))
	fmt.Println()

	// Print each section with differences
	for _, sd := range sectionDiffs {
		if len(sd.Diffs) == 0 {
			continue
		}

		// Section header
		cyan.Printf("%s\n", sd.Name)

		// Calculate max key width for alignment
		maxKeyWidth := 0
		maxLeftWidth := 0
		for _, fd := range sd.Diffs {
			if len(fd.Key) > maxKeyWidth {
				maxKeyWidth = len(fd.Key)
			}
			if len(fd.Left) > maxLeftWidth {
				maxLeftWidth = len(fd.Left)
			}
		}
		// Cap widths for readability
		if maxLeftWidth > 30 {
			maxLeftWidth = 30
		}

		// Print diffs
		for _, fd := range sd.Diffs {
			leftVal := truncate(fd.Left, 30)
			rightVal := truncate(fd.Right, 30)

			keyWithColon := fd.Key + ":"
			fmt.Printf("  %-*s  ", maxKeyWidth+1, keyWithColon)

			switch fd.Status {
			case "changed":
				yellow.Printf("%-*s", maxLeftWidth, leftVal)
				dim.Print("  →  ")
				green.Printf("%s\n", rightVal)
			case "removed":
				red.Printf("%-*s", maxLeftWidth, leftVal)
				dim.Print("  →  ")
				dim.Printf("%s\n", rightVal)
			case "added":
				dim.Printf("%-*s", maxLeftWidth, leftVal)
				dim.Print("  →  ")
				green.Printf("%s\n", rightVal)
			}
		}
		fmt.Println()
	}

	// Print common fields summary (optional, just count)
	commonCount := 0
	for _, sd := range sectionDiffs {
		commonCount += len(sd.Common)
	}

	// Summary
	dim.Printf("%d difference", totalDiffs)
	if totalDiffs != 1 {
		dim.Print("s")
	}
	dim.Printf(" found in %d section", sectionsWithDiffs)
	if sectionsWithDiffs != 1 {
		dim.Print("s")
	}
	if commonCount > 0 {
		dim.Printf(" (%d fields identical)", commonCount)
	}
	dim.Println(".")
	fmt.Println()

	return false
}

// truncate shortens a string if it exceeds maxLen.
func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	if maxLen <= 3 {
		return s[:maxLen]
	}
	return s[:maxLen-3] + "..."
}
