package output

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/ronalships/envsnap/internal/detector"
)

// Version is set at build time.
var Version = "dev"

// Markdown renders detector results to markdown format.
type Markdown struct {
	w io.Writer
}

// NewMarkdown creates a new Markdown renderer.
func NewMarkdown(w io.Writer) *Markdown {
	return &Markdown{w: w}
}

// Render writes all results as markdown.
func (m *Markdown) Render(results []detector.Result) error {
	// Header
	if _, err := fmt.Fprintf(m.w, "# Environment Snapshot\n\n"); err != nil {
		return err
	}

	// Metadata
	if _, err := fmt.Fprintf(m.w, "_Generated by envsnap %s at %s_\n\n",
		Version,
		time.Now().UTC().Format(time.RFC3339),
	); err != nil {
		return err
	}

	if _, err := fmt.Fprintf(m.w, "---\n\n"); err != nil {
		return err
	}

	// Each section
	for _, result := range results {
		if err := m.renderSection(result); err != nil {
			return err
		}
	}

	return nil
}

func (m *Markdown) renderSection(result detector.Result) error {
	// Section header
	if _, err := fmt.Fprintf(m.w, "## %s\n\n", result.Section); err != nil {
		return err
	}

	// Error notice if detection failed
	if result.Error != nil && len(result.Items) == 0 {
		if _, err := fmt.Fprintf(m.w, "_(detection failed: %s)_\n\n", result.Error); err != nil {
			return err
		}
		return nil
	}

	// No items
	if len(result.Items) == 0 {
		if _, err := fmt.Fprintf(m.w, "_No data detected_\n\n"); err != nil {
			return err
		}
		return nil
	}

	// Render as a table
	if _, err := fmt.Fprintf(m.w, "| Item | Value |\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(m.w, "|------|-------|\n"); err != nil {
		return err
	}

	for _, item := range result.Items {
		// Escape pipe characters in values
		key := escapeMarkdown(item.Key)
		value := escapeMarkdown(item.Value)

		if _, err := fmt.Fprintf(m.w, "| %s | %s |\n", key, value); err != nil {
			return err
		}
	}

	// Partial error notice
	if result.Error != nil {
		if _, err := fmt.Fprintf(m.w, "\n_(partial detection: %s)_\n", result.Error); err != nil {
			return err
		}
	}

	if _, err := fmt.Fprintf(m.w, "\n"); err != nil {
		return err
	}

	return nil
}

// escapeMarkdown escapes characters that have special meaning in markdown tables.
func escapeMarkdown(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", "")
	return s
}
